# Configures the server port for the USER Service
server:
  port: 9002

# Configures the Spring application name for the USER Service
spring:
  application:
    name: USER-SERVICE

  # The database connection details, and JPA/Hibernate settings.
  datasource:
    url: jdbc:mysql://localhost:3306/cims_user
    username: root
    password: Sheliya@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# Configures the Eureka client for the USER Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

# Configures management tracing for the application
management:
  tracing:
    sampling:
      probability: 1.0

# The file location paths for the CIMS project.
document:
  location: "C:/Users/MSI/Documents/Project/BSc/CIMS/File"
  max:
    image: 4000000
  document: "C:/Users/MSI/Documents/Project/BSc/CIMS/File/Document"
  history: "C:/Users/MSI/Documents/Project/BSc/CIMS/File/History"
  project: "C:/Users/MSI/Documents/Project/BSc/CIMS/File/Project"
