# Configures the server port for the PROJECT Service
server:
  port: 9005

# Configures the Spring application name for the PROJECT Service
spring:
  application:
    name: PROJECT-SERVICE

  # The database connection details, and JPA/Hibernate settings.
  datasource:
    url: jdbc:mysql://localhost:3306/cims_project
    username: root
    password: Sheliya@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# Configures the Eureka client for the PROJECT Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

# Configures management tracing for the application
management:
  tracing:
    sampling:
      probability: 1.0